# Generated by Django 4.2.9 on 2024-02-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_watchlist_plateform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplateform',
            name='about',
            field=models.TextField(max_length=45),
        ),
    ]
