# Generated by Django 4.2.9 on 2024-02-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_book',
            name='book_title',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
